stages:
    - install
    - test
    - publish
    - up-to-code

install:
    image: gcr.io/porch-gcp/node-build-agent:latest
    stage: install
    script:
       - npm install
    artifacts:
        expire_in: 1 hr
        paths:
            - node_modules/

lint:
    image: gcr.io/porch-gcp/node-build-agent:latest
    stage: test
    script:
        - npm run lint
    dependencies:
        - install

test:
    image: gcr.io/porch-gcp/node-build-agent:latest
    stage: test
    script:
        - npm test
    dependencies:
        - install

publish:
    image: gcr.io/porch-gcp/node-build-agent:latest
    stage: publish
    dependencies:
        - install
    only:
        - master
    script:
        - publish

up-to-code:
    image: gcr.io/porch-gcp/node-build-agent:latest
    stage: up-to-code
    services:
        - docker:dind
    only:
        - master
    script:
        - uptocode
