variables:
    BABEL_DISABLE_CACHE: "1"

.image: &node-build-agent-image
    image: gcr.io/porch-gcp/node-build-agent:6

stages:
    - install
    - test
    - publish
    - up-to-code

install:
    <<: *node-build-agent-image
    stage: install
    script:
       - yarn --no-lockfile
    artifacts:
        expire_in: 1 hr
        paths:
            - node_modules/

lint:
    <<: *node-build-agent-image
    stage: test
    script:
        - yarn lint
    dependencies:
        - install

test:
    <<: *node-build-agent-image
    stage: test
    script:
        - yarn test
    dependencies:
        - install

publish:
    <<: *node-build-agent-image
    stage: publish
    dependencies:
        - install
    only:
        - master
    script:
        - publish

up-to-code:
    <<: *node-build-agent-image
    stage: up-to-code
    services:
        - docker:dind
    only:
        - master
    script:
        - uptocode